includes:
- configs/water/base.yml

identifier: dpwater_dpp

model:
  name: dimenetplusplus
  hidden_channels: 64
  out_emb_channels: 64
  num_blocks: 3
  cutoff: 5.0
  num_radial: 4
  num_spherical: 4
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: True
  otf_graph: True

# *** Important note ***
#   The total number of gpus used for this run was 32.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 4
  eval_batch_size: 4
  num_workers: 4
  lr_initial: 0.001
  lr_gamma: 0.1
  optimizer: Adam
  ema_decay: 0.999
  # clip_grad_norm: 5.
  # lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
  #   - 520830
  #   - 833330
  #   - 1041660
  warmup_steps: 5000
  warmup_factor: 0.2
  max_epochs: 4000
  energy_coefficient: 1
  force_coefficient: 1000
  scheduler: ReduceLROnPlateau
  patience: 50
  factor: 0.1
  min_lr: 0.00000001
