T_init: 500.0
config_yml: !!python/object/apply:pathlib.PosixPath
- configs
- simulate
- aspirin.yml
dataset_src: DATAPATH/md17/aspirin/10k/test
deepmd: false
dp_data_path: DATAPATH/md17/aspirin/10k/DP/test
identifier: 300ps
integrator: NoseHoover
integrator_config:
  temperature: 500.0
  timestep: 0.5
  ttime: 20.0
kcal: false
max_test_points: 10000
model_dir: MODELPATH/md17-aspirin_10k_gemnet_t
nequip: false
nequip_data_config: configs/simulate/nequip_data_cfg/aspirin.yml
no_evaluate: false
plumed: false
purge: false
save_freq: 100
save_name: md_300ps_123
seed: 123
sim_type: ocp
steps: 600000
