trainer: trainer

dataset:
  src: /data/shared/MLFF/SPICE/maceoff_split/train
  name: spice
  size: ""
  normalize_labels: False

logger: 
  name: wandb
  project: mdbench

task:
  dataset: multi
  description: "Regressing to energies and forces"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

optim:
  early_stopping_time: 604800
  early_stopping_lr: 0.000001