amp: false
checkpoint: null
cpu: false
dataset:
- carbon_idx: 900000
  grad_target_mean: 0.0
  grad_target_std: 1.0
  molecule:
  - all_spice
  name: spice
  negate_force: false
  normalize_labels: true
  return_formation_energy: true
  size: all
  src: /data/shared/spice/maceoff_split
  # target_mean: -160.3177947998047
  # target_std: 1.0
# - src: /data/shared/MLFF/SPICE/maceoff_split/test
distributed: false
distributed_backend: nccl
distributed_port: 13356
finetuning: false
freeze_amount: max
freeze_rep: false
identifier: maceoff_split_testing_junk
is_debug: false
local_rank: 0
logger:
  name: wandb
  project: mdbench
mode: train
model:
  activation: silu
  cbf:
    name: spherical_harmonics
  cutoff: 5.0
  direct_forces: false
  emb_size_atom: 256
  emb_size_bil_trip: 64
  emb_size_cbf: 16
  emb_size_edge: 128
  emb_size_rbf: 32
  emb_size_trip: 64
  envelope:
    exponent: 5
    name: polynomial
  extensive: true
  max_neighbors: 50
  name: gemnet_t
  num_after_skip: 1
  num_atom: 2
  num_before_skip: 1
  num_blocks: 4
  num_concat: 1
  num_radial: 6
  num_spherical: 7
  otf_graph: true
  output_init: HeOrthogonal
  rbf:
    name: gaussian
  regress_forces: true
  scale_file: configs/spice/gemnet-T-scale.json
noddp: false
optim:
  batch_size: 128
  clip_grad_norm: 10
  early_stopping_lr: 1.0e-06
  early_stopping_time: 604800
  ema_decay: 0.999
  energy_coefficient: 40
  eval_batch_size: 128
  factor: 0.8
  force_coefficient: 1000
  loss_energy: mae
  loss_force: l2mae
  lr_initial: 0.001
  max_epochs: 250
  min_lr: 1.0e-06
  num_workers: 4
  optimizer: AdamW
  optimizer_params:
    amsgrad: true
    eps: 1.0e-07
    weight_decay: 2.0e-06
  patience: 5
  scheduler: ReduceLROnPlateau
percentage: 0.1 # we don't actually read this config file in the code (we change a value that's coded in, this is a fix we should make). i'm putting this here for my own sanity
print_every: 200
run_dir: MODELPATH/
seed: 0
submit: false
summit: false
task:
  dataset: multi
  description: Regressing to energies and forces
  eval_on_free_atoms: true
  grad_input: atomic forces
  labels:
  - potential energy
  metric: mae
  train_on_free_atoms: true
  type: regression
timestamp_id: null
trainer: trainer
world_size: 1
